# Generated by Django 3.2 on 2021-04-11 02:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_grupo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nome_produto', models.CharField(max_length=50)),
                ('descricao_produto', models.TextField()),
                ('preco_produto', models.FloatField()),
                ('data_cadastro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status_produto', models.BooleanField(default=False)),
                ('foto_produto', models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/')),
                ('grupo_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.grupo')),
            ],
        ),
    ]
